create table authors (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), address varchar(255), name varchar(255), url varchar(255), primary key (id)) engine=InnoDB;
create table authors_audit (id bigint not null, rev integer not null, revtype tinyint, address varchar(255), name varchar(255), url varchar(255), primary key (id, rev)) engine=InnoDB;
create table basket (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), customer_id bigint, primary key (id)) engine=InnoDB;
create table basket_audit (id bigint not null, rev integer not null, revtype tinyint, customer_id bigint, primary key (id, rev)) engine=InnoDB;
create table bb (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), count varchar(255), basket_id bigint, book_id bigint, primary key (id)) engine=InnoDB;
create table bb_audit (id bigint not null, rev integer not null, revtype tinyint, count varchar(255), basket_id bigint, book_id bigint, primary key (id, rev)) engine=InnoDB;
create table books (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), isbn varchar(255), price double precision, title varchar(255), year mediumint, author_id bigint, publisher_id bigint, primary key (id)) engine=InnoDB;
create table books_audit (id bigint not null, rev integer not null, revtype tinyint, isbn varchar(255), price double precision, title varchar(255), year mediumint, author_id bigint, publisher_id bigint, primary key (id, rev)) engine=InnoDB;
create table customers (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), address varchar(255), email varchar(255), name varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table customers_audit (id bigint not null, rev integer not null, revtype tinyint, address varchar(255), email varchar(255), name varchar(255), phone varchar(255), primary key (id, rev)) engine=InnoDB;
create table publisher (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), address varchar(255), name varchar(255), phone varchar(255), url varchar(255), primary key (id)) engine=InnoDB;
create table publisher_audit (id bigint not null, rev integer not null, revtype tinyint, address varchar(255), name varchar(255), phone varchar(255), url varchar(255), primary key (id, rev)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table warehouse (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), address varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table warehouse_audit (id bigint not null, rev integer not null, revtype tinyint, address varchar(255), phone varchar(255), primary key (id, rev)) engine=InnoDB;
create table wb (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), count varchar(255), book_id bigint, warehouse_id bigint, primary key (id)) engine=InnoDB;
create table wb_audit (id bigint not null, rev integer not null, revtype tinyint, count varchar(255), book_id bigint, warehouse_id bigint, primary key (id, rev)) engine=InnoDB;
alter table authors_audit add constraint FK4h9eexvqe2tf95cot5h3lmj2f foreign key (rev) references revinfo (rev);
alter table basket add constraint FKo6t593cbsl5m00yi1a68c9jxb foreign key (customer_id) references customers (id);
alter table basket_audit add constraint FKfan3fjd11k3iwngclcjy94hli foreign key (rev) references revinfo (rev);
alter table bb add constraint FKh9am91otml6oarhronvgitint foreign key (basket_id) references basket (id);
alter table bb add constraint FKhnwm13w4qkh0c4u4kati0no40 foreign key (book_id) references books (id);
alter table bb_audit add constraint FKmriuvbaawjj85tujjb3pemn9h foreign key (rev) references revinfo (rev);
alter table books add constraint FKfjixh2vym2cvfj3ufxj91jem7 foreign key (author_id) references authors (id);
alter table books add constraint FK1eujqvebj0cej9mcivv49grwi foreign key (publisher_id) references publisher (id);
alter table books_audit add constraint FKfyfj7ys56hvrijh5f6uklakbl foreign key (rev) references revinfo (rev);
alter table customers_audit add constraint FKomk36ryme5vkw0iwyfdqmrs3n foreign key (rev) references revinfo (rev);
alter table publisher_audit add constraint FKj7qitjv3h0lxkwmos2bfighst foreign key (rev) references revinfo (rev);
alter table warehouse_audit add constraint FKlyyfpxiyr1hv0jnpbtoob3l1q foreign key (rev) references revinfo (rev);
alter table wb add constraint FK748tkksfmoj536h3axoecmldf foreign key (book_id) references books (id);
alter table wb add constraint FKt0tgriu9dw2n5mmffbwvoyecg foreign key (warehouse_id) references warehouse (id);
alter table wb_audit add constraint FKjrxb67y0tjfo5u92c0xyfrmlk foreign key (rev) references revinfo (rev);